##### 用户个性化配置

# 普通抓取模式工作台参数
width_grab : 297  # 工作台宽度（机械臂开机时手臂的方向）
length_grab : 210  # 工作台长度
high_grab : 0  # 工作台高度
transform_x_grab : 100  # x方向(宽度)机械臂与工作台的偏移量

map_class_2_pos:  # 普通抓取模式，用户自定义的种类对应的目标点
  # 以下配置表示将工作台上的种类2抓取到[120,-190,30]点放置
  16:  # 目标种类
    high: 1  # 物体高度
    pos: [120,-160,30]  # 抓取目标点
  17:  # 目标种类
    high: 10  # 物体高度
    pos: [250,-160,30]  # 抓取目标点


# image_data文件夹下自己的数据集文件名,增加训练数据时不想覆盖原有数据时使用
data_name: "board_game"
# data_name: "items"   # 不想覆盖原有数据取消这里，注释上面的
