artifact_alias: latest
batch_size: 12
bbox_interval: -1
bucket: ''
cache: null
cfg: src/yolov5/models/yolov5s.yaml
cos_lr: false
data: src/yolov5/data/self_data.yaml
device: mps
entity: null
epochs: 5
evolve: null
exist_ok: false
freeze:
- 0
hyp: src/yolov5/data/hyps/hyp.scratch-low.yaml
image_weights: false
imgsz: 640
label_smoothing: 0.0
local_rank: -1
multi_scale: false
name: exp
noautoanchor: false
nosave: false
noval: false
optimizer: SGD
patience: 100
progressbar: null
project: src/yolov5/runs/train
quad: false
rect: false
resume: false
root: null
save_dir: src/yolov5/runs/train/exp10
save_period: -1
single_cls: false
sync_bn: false
upload_dataset: false
weights: /Users/bytedance/python/Fe-Fool/src/yolov5/runs/train/exp9/weights/last.pt
workers: 8
